import type {
  User,
  Account,
  Contact,
  Opportunity,
  Visit,
  VisitNote,
  RoutePlan,
} from "./types";

const NOW = new Date();

function daysAgo(n: number, hour = 14, minute = 0): Date {
  const d = new Date(NOW);
  d.setDate(d.getDate() - n);
  d.setHours(hour, minute, 0, 0);
  return d;
}

function todayAt(hour: number, minute = 0): Date {
  const d = new Date(NOW);
  d.setHours(hour, minute, 0, 0);
  return d;
}

// ============= Users =============
export const mockUsers: User[] = [
  {
    id: "usr-01",
    email: "yamada@demo.local",
    name: "山田 太郎",
    department: "営業1課",
    homeLat: 38.2682,
    homeLng: 140.8694,
    homeLabel: "仙台本社",
  },
  {
    id: "usr-02",
    email: "suzuki@demo.local",
    name: "鈴木 花子",
    department: "営業1課",
    homeLat: 38.2425,
    homeLng: 140.8859,
    homeLabel: "富沢営業所",
  },
];

// ============= Accounts =============
// acc-010 を 162日前にして停滞バッジ＋赤ピンの主役にする
export const mockAccounts: Account[] = [
  {
    id: "acc-001",
    name: "居酒屋 とまり木",
    nameKana: "イザカヤトマリギ",
    rank: "A",
    category: "居酒屋",
    billingAddress: "宮城県仙台市青葉区国分町2-8-15",
    geoLat: 38.2612,
    geoLng: 140.8719,
    phone: "022-222-1001",
    note: "米・地場野菜の定期納品先。新メニュー検討中",
    lastVisitAt: daysAgo(15),
    ownerId: "usr-01",
  },
  {
    id: "acc-002",
    name: "和食 瑞鳳",
    nameKana: "ワショクズイホウ",
    rank: "A",
    category: "割烹",
    billingAddress: "宮城県仙台市青葉区一番町3-6-1",
    geoLat: 38.2625,
    geoLng: 140.8712,
    phone: "022-222-1002",
    note: "ササニシキ定期納品。試食提案フェーズ",
    lastVisitAt: daysAgo(10),
    ownerId: "usr-01",
  },
  {
    id: "acc-003",
    name: "ビストロ ソレイユ",
    nameKana: "ビストロソレイユ",
    rank: "B",
    category: "レストラン",
    billingAddress: "宮城県仙台市青葉区木町通2-3-7",
    geoLat: 38.2701,
    geoLng: 140.8675,
    phone: "022-222-1003",
    note: "ひとめぼれブランド米の可能性を議論中",
    lastVisitAt: daysAgo(56),
    ownerId: "usr-01",
  },
  {
    id: "acc-004",
    name: "宮城野給食センター",
    nameKana: "ミヤギノキュウショクセンター",
    rank: "A",
    category: "給食",
    billingAddress: "宮城県仙台市宮城野区鶴ケ谷1-2-3",
    geoLat: 38.2908,
    geoLng: 140.9195,
    phone: "022-252-1004",
    note: "アレルギー対応米の問い合わせ中。年間契約",
    lastVisitAt: daysAgo(8),
    ownerId: "usr-02",
  },
  {
    id: "acc-005",
    name: "ホテル松島ビュー",
    nameKana: "ホテルマツシマビュー",
    rank: "A",
    category: "宿泊",
    billingAddress: "宮城県宮城郡松島町松島字町内77",
    geoLat: 38.3702,
    geoLng: 141.0648,
    phone: "022-354-1005",
    note: "朝食ビュッフェ用米の大口契約",
    lastVisitAt: daysAgo(44),
    ownerId: "usr-01",
  },
  {
    id: "acc-006",
    name: "スーパーフレッシュ泉店",
    nameKana: "スーパーフレッシュイズミテン",
    rank: "B",
    category: "小売",
    billingAddress: "宮城県仙台市泉区泉中央1-1-2",
    geoLat: 38.3169,
    geoLng: 140.8842,
    phone: "022-372-1006",
    note: "PB米の契約更新済み。野菜拡大余地あり",
    lastVisitAt: daysAgo(7),
    ownerId: "usr-02",
  },
  {
    id: "acc-007",
    name: "道の駅 村田",
    nameKana: "ミチノエキムラタ",
    rank: "C",
    category: "道の駅",
    billingAddress: "宮城県柴田郡村田町村田字土内4",
    geoLat: 38.1196,
    geoLng: 140.7381,
    phone: "0224-82-1007",
    note: "出品系。月次発注のみ。要フォロー",
    lastVisitAt: daysAgo(141),
    ownerId: "usr-02",
  },
  {
    id: "acc-008",
    name: "パン工房 麦の香",
    nameKana: "パンコウボウムギノカ",
    rank: "B",
    category: "製造小売",
    billingAddress: "宮城県仙台市太白区長町5-3-21",
    geoLat: 38.2288,
    geoLng: 140.8788,
    phone: "022-249-1008",
    note: "小麦の別ルート確保を相談中",
    lastVisitAt: daysAgo(5),
    ownerId: "usr-01",
  },
  {
    id: "acc-009",
    name: "旅館 ゆのはま",
    nameKana: "リョカンユノハマ",
    rank: "A",
    category: "宿泊",
    billingAddress: "宮城県仙台市太白区秋保町湯元字舘74",
    geoLat: 38.2321,
    geoLng: 140.7131,
    phone: "022-398-1009",
    note: "季節懐石の食材提案フェーズ",
    lastVisitAt: daysAgo(36),
    ownerId: "usr-02",
  },
  {
    id: "acc-010",
    name: "焼肉 大吉",
    nameKana: "ヤキニクダイキチ",
    rank: "A",
    category: "焼肉",
    billingAddress: "宮城県仙台市若林区荒町45",
    geoLat: 38.2548,
    geoLng: 140.8854,
    phone: "022-224-1010",
    note: "★162日未訪問。停滞 Account（デモの赤ピン候補）",
    lastVisitAt: daysAgo(162),
    ownerId: "usr-01",
  },
];

// ============= Contacts =============
export const mockContacts: Contact[] = [
  { id: "ctc-001", accountId: "acc-001", name: "田中 健一", nameKana: "タナカケンイチ", role: "店長", email: "tanaka@tomarigi.local", phone: "022-222-1001", isPrimary: true },
  { id: "ctc-002", accountId: "acc-002", name: "佐々木 真一", nameKana: "ササキシンイチ", role: "料理長", email: null, phone: "022-222-1002", isPrimary: true },
  { id: "ctc-003", accountId: "acc-003", name: "高橋 麻衣", nameKana: "タカハシマイ", role: "オーナーシェフ", email: null, phone: null, isPrimary: true },
  { id: "ctc-004", accountId: "acc-004", name: "佐藤 明子", nameKana: "サトウアキコ", role: "管理栄養士", email: "sato@miyagino-kyu.local", phone: "022-252-1004", isPrimary: true },
  { id: "ctc-005", accountId: "acc-005", name: "阿部 支配人", nameKana: "アベ", role: "支配人", email: null, phone: "022-354-1005", isPrimary: true },
  { id: "ctc-006", accountId: "acc-006", name: "小林 裕介", nameKana: "コバヤシユウスケ", role: "青果バイヤー", email: null, phone: "022-372-1006", isPrimary: true },
  { id: "ctc-007", accountId: "acc-007", name: "菅原 健", nameKana: "スガワラケン", role: "物産担当", email: null, phone: null, isPrimary: true },
  { id: "ctc-008", accountId: "acc-008", name: "伊藤 修", nameKana: "イトウオサム", role: "代表", email: null, phone: "022-249-1008", isPrimary: true },
  { id: "ctc-009", accountId: "acc-009", name: "遠藤 久美子", nameKana: "エンドウクミコ", role: "女将", email: null, phone: null, isPrimary: true },
  { id: "ctc-010", accountId: "acc-010", name: "小野寺 浩二", nameKana: "オノデラコウジ", role: "店長", email: null, phone: "022-224-1010", isPrimary: true },
];

// ============= Opportunities =============
export const mockOpportunities: Opportunity[] = [
  {
    id: "opp-001",
    accountId: "acc-002",
    title: "ササニシキ特別栽培米 月10俵契約",
    status: "OPEN",
    amount: 480000,
    dueDate: daysAgo(-14),
    nextAction: "サンプル送付後の試食結果ヒアリング",
    nextActionDate: daysAgo(-3),
  },
  {
    id: "opp-002",
    accountId: "acc-004",
    title: "アレルギー対応米 6月メニュー導入",
    status: "OPEN",
    amount: 1200000,
    dueDate: daysAgo(-21),
    nextAction: "グルテンフリー米粉の取引先候補ピックアップ",
    nextActionDate: daysAgo(-7),
  },
  {
    id: "opp-003",
    accountId: "acc-006",
    title: "PB米 年間契約更新",
    status: "WON",
    amount: 3600000,
    dueDate: daysAgo(7),
    nextAction: null,
    nextActionDate: null,
  },
];

// ============= Visits =============
export const mockVisits: Visit[] = [
  // 過去完了 5件
  {
    id: "vis-001",
    accountId: "acc-001",
    ownerId: "usr-01",
    status: "COMPLETED",
    purpose: "FOLLOW_UP",
    scheduledAt: daysAgo(15, 14, 0),
    arrivedAt: daysAgo(15, 14, 5),
    leftAt: daysAgo(15, 14, 45),
    durationMin: 40,
    arrivedLat: 38.2612, arrivedLng: 140.8719,
    routePlanId: null, opportunityId: null,
  },
  {
    id: "vis-002",
    accountId: "acc-002",
    ownerId: "usr-01",
    status: "COMPLETED",
    purpose: "NEW_PROPOSAL",
    scheduledAt: daysAgo(10, 11, 0),
    arrivedAt: daysAgo(10, 11, 2),
    leftAt: daysAgo(10, 11, 52),
    durationMin: 50,
    arrivedLat: 38.2625, arrivedLng: 140.8712,
    routePlanId: null, opportunityId: "opp-001",
  },
  {
    id: "vis-003",
    accountId: "acc-004",
    ownerId: "usr-02",
    status: "COMPLETED",
    purpose: "RELATIONSHIP",
    scheduledAt: daysAgo(8, 10, 0),
    arrivedAt: daysAgo(8, 10, 8),
    leftAt: daysAgo(8, 10, 58),
    durationMin: 50,
    arrivedLat: 38.2908, arrivedLng: 140.9195,
    routePlanId: null, opportunityId: "opp-002",
  },
  {
    id: "vis-004",
    accountId: "acc-006",
    ownerId: "usr-02",
    status: "COMPLETED",
    purpose: "CONTRACT",
    scheduledAt: daysAgo(7, 13, 30),
    arrivedAt: daysAgo(7, 13, 35),
    leftAt: daysAgo(7, 14, 25),
    durationMin: 50,
    arrivedLat: 38.3169, arrivedLng: 140.8842,
    routePlanId: null, opportunityId: "opp-003",
  },
  {
    id: "vis-005",
    accountId: "acc-008",
    ownerId: "usr-01",
    status: "COMPLETED",
    purpose: "FOLLOW_UP",
    scheduledAt: daysAgo(5, 15, 0),
    arrivedAt: daysAgo(5, 15, 2),
    leftAt: daysAgo(5, 15, 38),
    durationMin: 36,
    arrivedLat: 38.2288, arrivedLng: 140.8788,
    routePlanId: null, opportunityId: null,
  },
  // 今日の予定 3件
  {
    id: "vis-006",
    accountId: "acc-003",
    ownerId: "usr-01",
    status: "PLANNED",
    purpose: "NEW_PROPOSAL",
    scheduledAt: todayAt(10, 0),
    arrivedAt: null, leftAt: null, durationMin: null,
    arrivedLat: null, arrivedLng: null,
    routePlanId: "rp-001", opportunityId: null,
  },
  {
    id: "vis-007",
    accountId: "acc-005",
    ownerId: "usr-01",
    status: "PLANNED",
    purpose: "FOLLOW_UP",
    scheduledAt: todayAt(13, 30),
    arrivedAt: null, leftAt: null, durationMin: null,
    arrivedLat: null, arrivedLng: null,
    routePlanId: "rp-001", opportunityId: null,
  },
  {
    id: "vis-008",
    accountId: "acc-009",
    ownerId: "usr-02",
    status: "PLANNED",
    purpose: "RELATIONSHIP",
    scheduledAt: todayAt(14, 0),
    arrivedAt: null, leftAt: null, durationMin: null,
    arrivedLat: null, arrivedLng: null,
    routePlanId: null, opportunityId: null,
  },
];

// ============= VisitNotes =============
export const mockVisitNotes: VisitNote[] = [
  {
    id: "note-001", visitId: "vis-001", kind: "TEXT_TYPED",
    body: "田中店長と面談。来月から夜の新メニュー導入予定で米の使用量が1.3倍になる見込み。ひとめぼれ無洗米のサンプル希望。2週間後に見積もり送付予定。",
    audioUrl: null, transcribedAt: null,
    extractedNextAction: "見積もり送付", extractedNextActionDate: daysAgo(-1),
    promotedToOpportunity: false, createdAt: daysAgo(15, 14, 42),
  },
  {
    id: "note-002", visitId: "vis-002", kind: "TEXT_TYPED",
    body: "佐々木料理長にササニシキ特別栽培米を提案。試食は非常に好反応。来月頭からの定期納品に向けて来週500gのサンプル送付することで合意。",
    audioUrl: null, transcribedAt: null,
    extractedNextAction: "サンプル送付", extractedNextActionDate: daysAgo(-3),
    promotedToOpportunity: true, createdAt: daysAgo(10, 11, 50),
  },
  {
    id: "note-003", visitId: "vis-003", kind: "TEXT_TYPED",
    body: "佐藤栄養士と月次打ち合わせ。6月からアレルギー対応メニュー拡充の方針。グルテンフリー米粉の需要あり、次回までに仕入れ可能な取引先をピックアップ。",
    audioUrl: null, transcribedAt: null,
    extractedNextAction: "米粉取引先調査", extractedNextActionDate: daysAgo(-7),
    promotedToOpportunity: false, createdAt: daysAgo(8, 10, 55),
  },
  {
    id: "note-004", visitId: "vis-004", kind: "TEXT_TYPED",
    body: "小林バイヤーとPB米契約更新の交渉。年間契約で単価を見直す代わりに発注量保証の方向で合意。書面は本社法務経由で来週送付。野菜拡大の打診もあり別途提案資料準備。",
    audioUrl: null, transcribedAt: null,
    extractedNextAction: "PB契約書送付", extractedNextActionDate: daysAgo(-7),
    promotedToOpportunity: true, createdAt: daysAgo(7, 14, 22),
  },
  {
    id: "note-005", visitId: "vis-005", kind: "TEXT_TYPED",
    body: "伊藤オーナーから小麦仕入れ先の安定化について相談。昨年から主取引先の値上げが続いているとのこと。弊社の業務用小麦のラインと同業パン屋の事例を次回持参する。",
    audioUrl: null, transcribedAt: null,
    extractedNextAction: "小麦提案資料持参", extractedNextActionDate: daysAgo(-9),
    promotedToOpportunity: false, createdAt: daysAgo(5, 15, 35),
  },
];

// ============= RoutePlans =============
export const mockRoutePlans: RoutePlan[] = [
  {
    id: "rp-001",
    ownerId: "usr-01",
    planDate: todayAt(0, 0),
    status: "DRAFT",
    startLat: 38.2682, startLng: 140.8694, startLabel: "仙台本社",
    endLat: 38.2682, endLng: 140.8694, endLabel: "仙台本社",
    orderedVisitIds: "vis-006,vis-007",
    totalDistanceM: 85000,
    totalDurationS: 4200,
  },
];
