import type {
  User,
  Account,
  Contact,
  Opportunity,
  Visit,
  VisitNote,
  RoutePlan,
} from "./types";

const NOW = new Date();

function daysAgo(n: number, hour = 14, minute = 0): Date {
  const d = new Date(NOW);
  d.setDate(d.getDate() - n);
  d.setHours(hour, minute, 0, 0);
  return d;
}

function todayAt(hour: number, minute = 0): Date {
  const d = new Date(NOW);
  d.setHours(hour, minute, 0, 0);
  return d;
}

// ============= Users =============
export const mockUsers: User[] = [
  {
    id: "usr-01",
    email: "yamada@demo.local",
    name: "山田 太郎",
    department: "営業1課",
    homeLat: 35.6845,
    homeLng: 139.7649,
    homeLabel: "東京本社（大手町）",
  },
  {
    id: "usr-02",
    email: "suzuki@demo.local",
    name: "鈴木 花子",
    department: "営業1課",
    homeLat: 35.6262,
    homeLng: 139.7234,
    homeLabel: "五反田営業所",
  },
];

// ============= Accounts =============
// 東京23区＋多摩エリア。acc-005 を 32日前にして停滞バッジ＋赤ピンの主役にする
export const mockAccounts: Account[] = [
  {
    id: "acc-001",
    name: "居酒屋 とまり木",
    nameKana: "イザカヤトマリギ",
    rank: "A",
    category: "居酒屋",
    billingAddress: "東京都港区赤坂2-14-3",
    geoLat: 35.6720,
    geoLng: 139.7367,
    phone: "03-3585-1001",
    note: "米・地場野菜の定期納品先。新メニュー検討中",
    lastVisitAt: daysAgo(7),
    ownerId: "usr-01",
  },
  {
    id: "acc-002",
    name: "和食 瑞鳳",
    nameKana: "ワショクズイホウ",
    rank: "A",
    category: "割烹",
    billingAddress: "東京都中央区銀座5-9-12",
    geoLat: 35.6717,
    geoLng: 139.7656,
    phone: "03-3571-1002",
    note: "ササニシキ定期納品。試食提案フェーズ",
    lastVisitAt: daysAgo(4),
    ownerId: "usr-01",
  },
  {
    id: "acc-003",
    name: "ビストロ ソレイユ",
    nameKana: "ビストロソレイユ",
    rank: "B",
    category: "レストラン",
    billingAddress: "東京都渋谷区代官山町20-3",
    geoLat: 35.6498,
    geoLng: 139.7050,
    phone: "03-3464-1003",
    note: "ひとめぼれブランド米の可能性を議論中",
    lastVisitAt: daysAgo(3),
    ownerId: "usr-01",
  },
  {
    id: "acc-004",
    name: "豊洲給食センター",
    nameKana: "トヨスキュウショクセンター",
    rank: "A",
    category: "給食",
    billingAddress: "東京都江東区豊洲4-1-1",
    geoLat: 35.6553,
    geoLng: 139.7989,
    phone: "03-3520-1004",
    note: "アレルギー対応米の問い合わせ中。年間契約",
    lastVisitAt: daysAgo(11),
    ownerId: "usr-02",
  },
  {
    id: "acc-005",
    name: "ホテル品川シービュー",
    nameKana: "ホテルシナガワシービュー",
    rank: "A",
    category: "宿泊",
    billingAddress: "東京都港区高輪3-13-1",
    geoLat: 35.6280,
    geoLng: 139.7387,
    phone: "03-3447-1005",
    note: "朝食ビュッフェ用米の大口契約。シェフ会議の決裁待ちでフォロー要",
    lastVisitAt: daysAgo(32),
    ownerId: "usr-01",
  },
  {
    id: "acc-006",
    name: "スーパーフレッシュ三軒茶屋店",
    nameKana: "スーパーフレッシュサンゲンヂャヤテン",
    rank: "B",
    category: "小売",
    billingAddress: "東京都世田谷区三軒茶屋2-11-22",
    geoLat: 35.6438,
    geoLng: 139.6738,
    phone: "03-3414-1006",
    note: "PB米の契約更新済み。野菜拡大余地あり",
    lastVisitAt: daysAgo(9),
    ownerId: "usr-02",
  },
  {
    id: "acc-007",
    name: "道の駅 八王子滝山",
    nameKana: "ミチノエキハチオウジタキヤマ",
    rank: "C",
    category: "道の駅",
    billingAddress: "東京都八王子市滝山町1-592-2",
    geoLat: 35.6938,
    geoLng: 139.3500,
    phone: "042-696-1007",
    note: "出品系。月次発注のみ。要フォロー",
    lastVisitAt: daysAgo(141),
    ownerId: "usr-02",
  },
  {
    id: "acc-008",
    name: "パン工房 麦の香",
    nameKana: "パンコウボウムギノカ",
    rank: "B",
    category: "製造小売",
    billingAddress: "東京都杉並区荻窪5-15-3",
    geoLat: 35.7050,
    geoLng: 139.6196,
    phone: "03-3398-1008",
    note: "小麦の別ルート確保を相談中",
    lastVisitAt: daysAgo(1),
    ownerId: "usr-01",
  },
  {
    id: "acc-009",
    name: "旅館 つる屋",
    nameKana: "リョカンツルヤ",
    rank: "A",
    category: "宿泊",
    billingAddress: "東京都中央区銀座8-7-19",
    geoLat: 35.6680,
    geoLng: 139.7635,
    phone: "03-3571-1009",
    note: "季節懐石の食材提案フェーズ",
    lastVisitAt: daysAgo(5),
    ownerId: "usr-02",
  },
];

// ============= Contacts =============
export const mockContacts: Contact[] = [
  { id: "ctc-001", accountId: "acc-001", name: "田中 健一", nameKana: "タナカケンイチ", role: "店長", email: "tanaka@tomarigi.local", phone: "03-3585-1001", isPrimary: true },
  { id: "ctc-002", accountId: "acc-001", name: "山口 洋介", nameKana: "ヤマグチヨウスケ", role: "マネージャー", email: null, phone: null, isPrimary: false },
  { id: "ctc-003", accountId: "acc-002", name: "佐々木 真一", nameKana: "ササキシンイチ", role: "料理長", email: null, phone: "03-3571-1002", isPrimary: true },
  { id: "ctc-004", accountId: "acc-002", name: "大久保 仁", nameKana: "オオクボヒトシ", role: "オーナー", email: null, phone: null, isPrimary: false },
  { id: "ctc-005", accountId: "acc-003", name: "高橋 麻衣", nameKana: "タカハシマイ", role: "オーナーシェフ", email: null, phone: null, isPrimary: true },
  { id: "ctc-006", accountId: "acc-004", name: "佐藤 明子", nameKana: "サトウアキコ", role: "管理栄養士", email: "sato@toyosu-kyu.local", phone: "03-3520-1004", isPrimary: true },
  { id: "ctc-007", accountId: "acc-004", name: "木村 浩平", nameKana: "キムラコウヘイ", role: "施設長", email: null, phone: null, isPrimary: false },
  { id: "ctc-008", accountId: "acc-005", name: "阿部 支配人", nameKana: "アベ", role: "支配人", email: null, phone: "03-3447-1005", isPrimary: true },
  { id: "ctc-009", accountId: "acc-005", name: "中村 美咲", nameKana: "ナカムラミサキ", role: "料飲統括", email: null, phone: null, isPrimary: false },
  { id: "ctc-010", accountId: "acc-006", name: "小林 裕介", nameKana: "コバヤシユウスケ", role: "青果バイヤー", email: null, phone: "03-3414-1006", isPrimary: true },
  { id: "ctc-011", accountId: "acc-007", name: "菅原 健", nameKana: "スガワラケン", role: "物産担当", email: null, phone: null, isPrimary: true },
  { id: "ctc-012", accountId: "acc-008", name: "伊藤 修", nameKana: "イトウオサム", role: "代表", email: null, phone: "03-3398-1008", isPrimary: true },
  { id: "ctc-013", accountId: "acc-009", name: "遠藤 久美子", nameKana: "エンドウクミコ", role: "女将", email: null, phone: null, isPrimary: true },
];

// ============= Opportunities =============
export const mockOpportunities: Opportunity[] = [
  {
    id: "opp-001",
    accountId: "acc-002",
    title: "ササニシキ特別栽培米 月10俵契約",
    status: "OPEN",
    amount: 480000,
    dueDate: daysAgo(-14),
    nextAction: "サンプル送付後の試食結果ヒアリング",
    nextActionDate: daysAgo(-3),
  },
  {
    id: "opp-002",
    accountId: "acc-004",
    title: "アレルギー対応米 6月メニュー導入",
    status: "OPEN",
    amount: 1200000,
    dueDate: daysAgo(-21),
    nextAction: "グルテンフリー米粉の取引先候補ピックアップ",
    nextActionDate: daysAgo(-7),
  },
  {
    id: "opp-003",
    accountId: "acc-006",
    title: "PB米 年間契約更新",
    status: "WON",
    amount: 3600000,
    dueDate: daysAgo(7),
    nextAction: null,
    nextActionDate: null,
  },
  {
    id: "opp-004",
    accountId: "acc-001",
    title: "新メニュー用ひとめぼれ無洗米",
    status: "OPEN",
    amount: 240000,
    dueDate: daysAgo(-28),
    nextAction: "見積もり提出と試食日程調整",
    nextActionDate: daysAgo(-5),
  },
  {
    id: "opp-005",
    accountId: "acc-005",
    title: "朝食ビュッフェ向け 八重原コシヒカリ",
    status: "OPEN",
    amount: 1800000,
    dueDate: daysAgo(-35),
    nextAction: "シェフ会議向けプレゼン資料準備",
    nextActionDate: daysAgo(-10),
  },
  {
    id: "opp-006",
    accountId: "acc-009",
    title: "季節懐石コース食材一括提案",
    status: "OPEN",
    amount: 850000,
    dueDate: daysAgo(-42),
    nextAction: "夏メニュー試作品 第2回試食会",
    nextActionDate: daysAgo(-12),
  },
];

// ============= Visits =============
// 過去訪問 12件 + 今日の予定 4件 = 16件
export const mockVisits: Visit[] = [
  // 過去完了 - 古い順
  {
    id: "vis-001",
    accountId: "acc-001",
    ownerId: "usr-01",
    status: "COMPLETED",
    purpose: "FOLLOW_UP",
    scheduledAt: daysAgo(20, 14, 0),
    arrivedAt: daysAgo(20, 14, 5),
    leftAt: daysAgo(20, 14, 45),
    durationMin: 40,
    arrivedLat: 35.6720, arrivedLng: 139.7367,
    routePlanId: null, opportunityId: null,
  },
  {
    id: "vis-002",
    accountId: "acc-002",
    ownerId: "usr-01",
    status: "COMPLETED",
    purpose: "NEW_PROPOSAL",
    scheduledAt: daysAgo(18, 11, 0),
    arrivedAt: daysAgo(18, 11, 2),
    leftAt: daysAgo(18, 11, 52),
    durationMin: 50,
    arrivedLat: 35.6717, arrivedLng: 139.7656,
    routePlanId: null, opportunityId: "opp-001",
  },
  {
    id: "vis-003",
    accountId: "acc-005",
    ownerId: "usr-01",
    status: "COMPLETED",
    purpose: "NEW_PROPOSAL",
    scheduledAt: daysAgo(45, 10, 0),
    arrivedAt: daysAgo(45, 10, 8),
    leftAt: daysAgo(45, 11, 8),
    durationMin: 60,
    arrivedLat: 35.6280, arrivedLng: 139.7387,
    routePlanId: null, opportunityId: "opp-005",
  },
  {
    id: "vis-004",
    accountId: "acc-004",
    ownerId: "usr-02",
    status: "COMPLETED",
    purpose: "RELATIONSHIP",
    scheduledAt: daysAgo(11, 10, 0),
    arrivedAt: daysAgo(11, 10, 8),
    leftAt: daysAgo(11, 10, 58),
    durationMin: 50,
    arrivedLat: 35.6553, arrivedLng: 139.7989,
    routePlanId: null, opportunityId: "opp-002",
  },
  {
    id: "vis-005",
    accountId: "acc-006",
    ownerId: "usr-02",
    status: "COMPLETED",
    purpose: "CONTRACT",
    scheduledAt: daysAgo(9, 13, 30),
    arrivedAt: daysAgo(9, 13, 35),
    leftAt: daysAgo(9, 14, 25),
    durationMin: 50,
    arrivedLat: 35.6438, arrivedLng: 139.6738,
    routePlanId: null, opportunityId: "opp-003",
  },
  {
    id: "vis-006",
    accountId: "acc-001",
    ownerId: "usr-01",
    status: "COMPLETED",
    purpose: "NEW_PROPOSAL",
    scheduledAt: daysAgo(7, 15, 0),
    arrivedAt: daysAgo(7, 15, 3),
    leftAt: daysAgo(7, 15, 38),
    durationMin: 35,
    arrivedLat: 35.6720, arrivedLng: 139.7367,
    routePlanId: null, opportunityId: "opp-004",
  },
  {
    id: "vis-007",
    accountId: "acc-009",
    ownerId: "usr-02",
    status: "COMPLETED",
    purpose: "RELATIONSHIP",
    scheduledAt: daysAgo(5, 14, 0),
    arrivedAt: daysAgo(5, 14, 4),
    leftAt: daysAgo(5, 14, 49),
    durationMin: 45,
    arrivedLat: 35.6680, arrivedLng: 139.7635,
    routePlanId: null, opportunityId: "opp-006",
  },
  {
    id: "vis-008",
    accountId: "acc-002",
    ownerId: "usr-01",
    status: "COMPLETED",
    purpose: "FOLLOW_UP",
    scheduledAt: daysAgo(4, 11, 30),
    arrivedAt: daysAgo(4, 11, 33),
    leftAt: daysAgo(4, 12, 13),
    durationMin: 40,
    arrivedLat: 35.6717, arrivedLng: 139.7656,
    routePlanId: null, opportunityId: "opp-001",
  },
  {
    id: "vis-009",
    accountId: "acc-003",
    ownerId: "usr-01",
    status: "COMPLETED",
    purpose: "NEW_PROPOSAL",
    scheduledAt: daysAgo(3, 14, 30),
    arrivedAt: daysAgo(3, 14, 33),
    leftAt: daysAgo(3, 15, 3),
    durationMin: 30,
    arrivedLat: 35.6498, arrivedLng: 139.7050,
    routePlanId: null, opportunityId: null,
  },
  {
    id: "vis-010",
    accountId: "acc-005",
    ownerId: "usr-01",
    status: "COMPLETED",
    purpose: "FOLLOW_UP",
    scheduledAt: daysAgo(32, 10, 0),
    arrivedAt: daysAgo(32, 10, 5),
    leftAt: daysAgo(32, 10, 45),
    durationMin: 40,
    arrivedLat: 35.6280, arrivedLng: 139.7387,
    routePlanId: null, opportunityId: "opp-005",
  },
  {
    id: "vis-011",
    accountId: "acc-008",
    ownerId: "usr-01",
    status: "COMPLETED",
    purpose: "FOLLOW_UP",
    scheduledAt: daysAgo(1, 15, 0),
    arrivedAt: daysAgo(1, 15, 2),
    leftAt: daysAgo(1, 15, 38),
    durationMin: 36,
    arrivedLat: 35.7050, arrivedLng: 139.6196,
    routePlanId: null, opportunityId: null,
  },
  {
    id: "vis-012",
    accountId: "acc-004",
    ownerId: "usr-02",
    status: "COMPLETED",
    purpose: "FOLLOW_UP",
    scheduledAt: daysAgo(1, 13, 0),
    arrivedAt: daysAgo(1, 13, 5),
    leftAt: daysAgo(1, 13, 45),
    durationMin: 40,
    arrivedLat: 35.6553, arrivedLng: 139.7989,
    routePlanId: null, opportunityId: "opp-002",
  },
  // 今日の予定 4件
  {
    id: "vis-013",
    accountId: "acc-006",
    ownerId: "usr-02",
    status: "PLANNED",
    purpose: "RELATIONSHIP",
    scheduledAt: todayAt(9, 30),
    arrivedAt: null, leftAt: null, durationMin: null,
    arrivedLat: null, arrivedLng: null,
    routePlanId: null, opportunityId: null,
  },
  {
    id: "vis-014",
    accountId: "acc-001",
    ownerId: "usr-01",
    status: "PLANNED",
    purpose: "FOLLOW_UP",
    scheduledAt: todayAt(10, 30),
    arrivedAt: null, leftAt: null, durationMin: null,
    arrivedLat: null, arrivedLng: null,
    routePlanId: "rp-001", opportunityId: "opp-004",
  },
  {
    id: "vis-015",
    accountId: "acc-002",
    ownerId: "usr-01",
    status: "PLANNED",
    purpose: "NEW_PROPOSAL",
    scheduledAt: todayAt(13, 30),
    arrivedAt: null, leftAt: null, durationMin: null,
    arrivedLat: null, arrivedLng: null,
    routePlanId: "rp-001", opportunityId: "opp-001",
  },
  {
    id: "vis-016",
    accountId: "acc-009",
    ownerId: "usr-02",
    status: "PLANNED",
    purpose: "RELATIONSHIP",
    scheduledAt: todayAt(14, 0),
    arrivedAt: null, leftAt: null, durationMin: null,
    arrivedLat: null, arrivedLng: null,
    routePlanId: null, opportunityId: "opp-006",
  },
];

// ============= VisitNotes =============
// 過去訪問にすべてノート、複数訪問の取引先には経緯が見えるストーリー仕立て
export const mockVisitNotes: VisitNote[] = [
  {
    id: "note-001", visitId: "vis-001", kind: "TEXT_TYPED",
    body: "田中店長と面談。月次定期。米の在庫消化はいいペースだが、新メニュー導入の予定があり、6月から発注量が1.3倍程度になる見込みとのこと。次回までに無洗米サンプルを準備。",
    audioUrl: null, transcribedAt: null,
    extractedNextAction: "ひとめぼれ無洗米サンプル準備", extractedNextActionDate: daysAgo(-14),
    promotedToOpportunity: false, createdAt: daysAgo(20, 14, 42),
  },
  {
    id: "note-002", visitId: "vis-002", kind: "TEXT_TYPED",
    body: "佐々木料理長にササニシキ特別栽培米を提案。試食は非常に好評、シェフ全員が新規導入賛成。月10俵相当（48万/月）の規模感で来月頭からの定期契約を目指す。サンプル500g送付で合意。",
    audioUrl: null, transcribedAt: null,
    extractedNextAction: "サンプル送付", extractedNextActionDate: daysAgo(-3),
    promotedToOpportunity: true, createdAt: daysAgo(18, 11, 53),
  },
  {
    id: "note-003", visitId: "vis-003", kind: "VOICE_CLEANED",
    body: "阿部支配人にシェフを交えて朝食ビュッフェ向け米の入れ替えを提案。現状コストは月150万、八重原コシヒカリで品質UPかつコスト維持の試算を提示。シェフ会議で諮るとのこと。次回プレゼン資料を準備。",
    audioUrl: null, transcribedAt: daysAgo(45, 11, 15),
    extractedNextAction: "シェフ会議向け資料準備", extractedNextActionDate: daysAgo(-10),
    promotedToOpportunity: true, createdAt: daysAgo(45, 11, 8),
  },
  {
    id: "note-004", visitId: "vis-004", kind: "TEXT_TYPED",
    body: "佐藤栄養士と月次打ち合わせ。6月からアレルギー対応メニュー拡充の方針が確定。グルテンフリー米粉の需要あり、次回までに仕入れ可能な取引先を3社ピックアップして比較表を作る。",
    audioUrl: null, transcribedAt: null,
    extractedNextAction: "米粉取引先3社比較表", extractedNextActionDate: daysAgo(-7),
    promotedToOpportunity: false, createdAt: daysAgo(11, 10, 55),
  },
  {
    id: "note-005", visitId: "vis-005", kind: "TEXT_TYPED",
    body: "小林バイヤーとPB米年間契約更新の最終交渉。年間契約で単価を見直す代わりに発注量保証の方向で合意。書面は本社法務経由で来週送付。野菜拡大の打診もあり別途提案資料準備。",
    audioUrl: null, transcribedAt: null,
    extractedNextAction: "PB契約書送付", extractedNextActionDate: daysAgo(-1),
    promotedToOpportunity: true, createdAt: daysAgo(9, 14, 22),
  },
  {
    id: "note-006", visitId: "vis-006", kind: "VOICE_CLEANED",
    body: "田中店長フォロー訪問。前回提案したひとめぼれ無洗米サンプルの試食結果は好印象。新メニュー導入時期は7月で確定、見積もり提出と試食イベント日程を進める。山口マネージャーも同席で前向き。",
    audioUrl: null, transcribedAt: daysAgo(7, 15, 50),
    extractedNextAction: "見積もり提出と試食日程", extractedNextActionDate: daysAgo(-5),
    promotedToOpportunity: true, createdAt: daysAgo(7, 15, 38),
  },
  {
    id: "note-007", visitId: "vis-007", kind: "TEXT_TYPED",
    body: "遠藤女将から夏メニュー向けの食材提案を相談。山形米と契約農家野菜の組み合わせを推奨、見本を6月初旬に送付予定。一括契約化で月70万規模の可能性。試作品の試食会は再来週。",
    audioUrl: null, transcribedAt: null,
    extractedNextAction: "見本送付＆試食会調整", extractedNextActionDate: daysAgo(-12),
    promotedToOpportunity: true, createdAt: daysAgo(5, 14, 50),
  },
  {
    id: "note-008", visitId: "vis-008", kind: "TEXT_TYPED",
    body: "佐々木料理長のフォロー。先週のサンプル試食結果はオーナーの大久保さんも好印象、契約方向で確定。あとは4月分の発注量と引き渡しタイミングの調整のみ。次回訪問で書面に。",
    audioUrl: null, transcribedAt: null,
    extractedNextAction: "発注量・タイミング調整書", extractedNextActionDate: daysAgo(-3),
    promotedToOpportunity: false, createdAt: daysAgo(4, 12, 13),
  },
  {
    id: "note-009", visitId: "vis-009", kind: "TEXT_TYPED",
    body: "高橋シェフへ初回提案訪問。ひとめぼれブランド米の特徴と、競合他社との差別化ポイントを説明。シェフは興味あり、次回はソムリエも交えて再度相談したいとのこと。素材提案リストを送付。",
    audioUrl: null, transcribedAt: null,
    extractedNextAction: "素材提案リスト送付", extractedNextActionDate: daysAgo(-7),
    promotedToOpportunity: false, createdAt: daysAgo(3, 15, 5),
  },
  {
    id: "note-010", visitId: "vis-010", kind: "VOICE_CLEANED",
    body: "ホテル品川シービュー、阿部支配人と中村氏。シェフ会議の資料一式を持参、コシヒカリ提案へ前向きな反応。価格レンジOK、最終決裁は支配人で来月中に判断。試食会日程調整中。",
    audioUrl: null, transcribedAt: daysAgo(32, 10, 50),
    extractedNextAction: "試食会日程調整＆フォロー連絡", extractedNextActionDate: daysAgo(-15),
    promotedToOpportunity: false, createdAt: daysAgo(32, 10, 45),
  },
  {
    id: "note-011", visitId: "vis-011", kind: "TEXT_TYPED",
    body: "伊藤代表から小麦仕入れ先の安定化について再度相談。昨年から主取引先の値上げが続いているとのこと。弊社の業務用小麦のラインと同業パン屋の事例を次回持参。価格の概算も提示。",
    audioUrl: null, transcribedAt: null,
    extractedNextAction: "小麦提案資料持参", extractedNextActionDate: daysAgo(-9),
    promotedToOpportunity: false, createdAt: daysAgo(1, 15, 35),
  },
  {
    id: "note-012", visitId: "vis-012", kind: "TEXT_TYPED",
    body: "佐藤栄養士と前回提案の続き。グルテンフリー米粉3社比較表を持参、A社の品質と価格バランスが良いと評価。施設長の木村さんも交えて6月導入の方針で合意。発注量と試験運用範囲を決定。",
    audioUrl: null, transcribedAt: null,
    extractedNextAction: "A社米粉サンプル取り寄せ", extractedNextActionDate: daysAgo(-7),
    promotedToOpportunity: false, createdAt: daysAgo(1, 13, 45),
  },
];

// ============= RoutePlans =============
export const mockRoutePlans: RoutePlan[] = [
  {
    id: "rp-001",
    ownerId: "usr-01",
    planDate: todayAt(0, 0),
    status: "DRAFT",
    startLat: 35.6845, startLng: 139.7649, startLabel: "東京本社（大手町）",
    endLat: 35.6845, endLng: 139.7649, endLabel: "東京本社（大手町）",
    orderedVisitIds: "vis-014,vis-015",
    totalDistanceM: 12000,
    totalDurationS: 2100,
  },
];
