import type {
  User,
  Account,
  Contact,
  Opportunity,
  Visit,
  VisitNote,
  RoutePlan,
} from "./types";

const NOW = new Date();

function daysAgo(n: number, hour = 14, minute = 0): Date {
  const d = new Date(NOW);
  d.setDate(d.getDate() - n);
  d.setHours(hour, minute, 0, 0);
  return d;
}

function todayAt(hour: number, minute = 0): Date {
  const d = new Date(NOW);
  d.setHours(hour, minute, 0, 0);
  return d;
}

// ============= Users =============
// 産廃業者の営業（久留米市拠点）
export const mockUsers: User[] = [
  {
    id: "usr-01",
    email: "tanaka@demo.local",
    name: "田中 健司",
    department: "営業1課",
    homeLat: 33.3194,
    homeLng: 130.5092,
    homeLabel: "久留米本社（JR久留米駅前）",
  },
  {
    id: "usr-02",
    email: "sato@demo.local",
    name: "佐藤 香織",
    department: "営業1課",
    homeLat: 33.3833,
    homeLng: 130.4972,
    homeLabel: "鳥栖営業所",
  },
];

// ============= Accounts =============
// 久留米市〜近郊の建築・解体・工場・オフィスビル系の取引先
export const mockAccounts: Account[] = [
  {
    id: "acc-001",
    name: "大野建築",
    nameKana: "オオノケンチク",
    rank: "A",
    category: "工務店",
    billingAddress: "福岡県久留米市諏訪野町1234-5",
    geoLat: 33.3142,
    geoLng: 130.5122,
    phone: "0942-31-1001",
    note: "新築・改築の現場が多く、廃材の月次回収契約あり",
    lastVisitAt: daysAgo(7),
    ownerId: "usr-01",
  },
  {
    id: "acc-002",
    name: "リフォーム八女工房",
    nameKana: "リフォームヤメコウボウ",
    rank: "A",
    category: "リフォーム",
    billingAddress: "福岡県八女市本町302",
    geoLat: 33.2117,
    geoLng: 130.5586,
    phone: "0943-22-1002",
    note: "解体材の分別効率化を相談中。木材・石膏ボード・金属の3区分で見積中",
    lastVisitAt: daysAgo(4),
    ownerId: "usr-02",
  },
  {
    id: "acc-003",
    name: "久留米精工",
    nameKana: "クルメセイコウ",
    rank: "B",
    category: "金属加工",
    billingAddress: "福岡県久留米市津福本町789",
    geoLat: 33.2988,
    geoLng: 130.5226,
    phone: "0942-32-1003",
    note: "金属屑（鉄・アルミ・銅）の買取単価を交渉。月次引取",
    lastVisitAt: daysAgo(3),
    ownerId: "usr-01",
  },
  {
    id: "acc-004",
    name: "昭和解体工業",
    nameKana: "ショウワカイタイコウギョウ",
    rank: "A",
    category: "解体",
    billingAddress: "福岡県久留米市北野町12-1",
    geoLat: 33.3700,
    geoLng: 130.5862,
    phone: "0942-78-1004",
    note: "木造解体・RC解体の混合廃棄物。マニフェスト電子化を推進中",
    lastVisitAt: daysAgo(11),
    ownerId: "usr-02",
  },
  {
    id: "acc-005",
    name: "シティタワー久留米管理",
    nameKana: "シティタワークルメカンリ",
    rank: "A",
    category: "オフィスビル管理",
    billingAddress: "福岡県久留米市東町45-2",
    geoLat: 33.3187,
    geoLng: 130.5126,
    phone: "0942-30-1005",
    note: "テナント26社入居。書類・什器の定期回収（週2回）。シュレッダー回収も併用",
    lastVisitAt: daysAgo(32),
    ownerId: "usr-01",
  },
  {
    id: "acc-006",
    name: "太田鉄工所",
    nameKana: "オオタテッコウショ",
    rank: "B",
    category: "鉄工所",
    billingAddress: "福岡県久留米市田主丸町567",
    geoLat: 33.3768,
    geoLng: 130.6537,
    phone: "0943-72-1006",
    note: "切粉・スクラップの月次引取。昇降機の更新で発生量増加見込み",
    lastVisitAt: daysAgo(9),
    ownerId: "usr-02",
  },
  {
    id: "acc-007",
    name: "筑後リサイクルセンター",
    nameKana: "チクゴリサイクルセンター",
    rank: "C",
    category: "同業連携",
    billingAddress: "福岡県三潴郡大木町2345",
    geoLat: 33.2533,
    geoLng: 130.5500,
    phone: "0944-32-1007",
    note: "選別後の中間処分の引き取り先。月次調整のみ、深い営業は不要",
    lastVisitAt: daysAgo(141),
    ownerId: "usr-02",
  },
  {
    id: "acc-008",
    name: "アライ総合建設",
    nameKana: "アライソウゴウケンセツ",
    rank: "A",
    category: "総合建設",
    billingAddress: "福岡県久留米市国分町890",
    geoLat: 33.3245,
    geoLng: 130.5275,
    phone: "0942-43-1008",
    note: "公共工事も多い、年間契約。混合廃棄物の現場分別を継続改善",
    lastVisitAt: daysAgo(5),
    ownerId: "usr-01",
  },
  {
    id: "acc-009",
    name: "久留米中央ビル",
    nameKana: "クルメチュウオウビル",
    rank: "B",
    category: "複合オフィス",
    billingAddress: "福岡県久留米市本町10-1",
    geoLat: 33.3201,
    geoLng: 130.5145,
    phone: "0942-30-1009",
    note: "機密書類のシュレッダー回収。月次でマニフェスト発行",
    lastVisitAt: daysAgo(1),
    ownerId: "usr-01",
  },
  {
    id: "acc-010",
    name: "西鉄リフォーム",
    nameKana: "ニシテツリフォーム",
    rank: "A",
    category: "リフォーム",
    billingAddress: "福岡県久留米市南薫町300",
    geoLat: 33.3076,
    geoLng: 130.5186,
    phone: "0942-37-1010",
    note: "店舗リフォーム中心。マニフェスト電子化導入を提案中",
    lastVisitAt: daysAgo(2),
    ownerId: "usr-01",
  },
];

// ============= Contacts =============
export const mockContacts: Contact[] = [
  { id: "ctc-001", accountId: "acc-001", name: "大野 浩司", nameKana: "オオノコウジ", role: "代表取締役", email: "ohno@oono-kenchiku.local", phone: "0942-31-1001", isPrimary: true },
  { id: "ctc-002", accountId: "acc-001", name: "中村 工務", nameKana: "ナカムラコウム", role: "現場監督", email: null, phone: null, isPrimary: false },
  { id: "ctc-003", accountId: "acc-002", name: "田川 健", nameKana: "タガワケン", role: "工房長", email: null, phone: "0943-22-1002", isPrimary: true },
  { id: "ctc-004", accountId: "acc-002", name: "高木 真理", nameKana: "タカギマリ", role: "施工管理", email: null, phone: null, isPrimary: false },
  { id: "ctc-005", accountId: "acc-003", name: "山内 賢一", nameKana: "ヤマウチケンイチ", role: "工場長", email: null, phone: null, isPrimary: true },
  { id: "ctc-006", accountId: "acc-004", name: "古賀 信夫", nameKana: "コガノブオ", role: "代表", email: "koga@showa-kaitai.local", phone: "0942-78-1004", isPrimary: true },
  { id: "ctc-007", accountId: "acc-004", name: "井上 武", nameKana: "イノウエタケシ", role: "現場責任者", email: null, phone: null, isPrimary: false },
  { id: "ctc-008", accountId: "acc-005", name: "高橋 由美", nameKana: "タカハシユミ", role: "管理責任者", email: null, phone: "0942-30-1005", isPrimary: true },
  { id: "ctc-009", accountId: "acc-005", name: "松尾 達也", nameKana: "マツオタツヤ", role: "設備担当", email: null, phone: null, isPrimary: false },
  { id: "ctc-010", accountId: "acc-006", name: "太田 雅彦", nameKana: "オオタマサヒコ", role: "工場長", email: null, phone: "0943-72-1006", isPrimary: true },
  { id: "ctc-011", accountId: "acc-007", name: "藤本 隆", nameKana: "フジモトタカシ", role: "業務担当", email: null, phone: null, isPrimary: true },
  { id: "ctc-012", accountId: "acc-008", name: "新井 雄一", nameKana: "アライユウイチ", role: "工事部長", email: "arai@arai-kensetsu.local", phone: "0942-43-1008", isPrimary: true },
  { id: "ctc-013", accountId: "acc-009", name: "永田 隆", nameKana: "ナガタタカシ", role: "ビル管理長", email: null, phone: "0942-30-1009", isPrimary: true },
  { id: "ctc-014", accountId: "acc-010", name: "永野 幸男", nameKana: "ナガノユキオ", role: "店長", email: null, phone: "0942-37-1010", isPrimary: true },
  { id: "ctc-015", accountId: "acc-010", name: "草野 友里", nameKana: "クサノユリ", role: "工程管理", email: null, phone: null, isPrimary: false },
];

// ============= Opportunities =============
export const mockOpportunities: Opportunity[] = [
  {
    id: "opp-001",
    accountId: "acc-002",
    title: "解体材3区分（木材・石膏ボード・金属）月次契約",
    status: "OPEN",
    amount: 480000,
    dueDate: daysAgo(-14),
    nextAction: "見積後の現場立会いと初回回収日の確定",
    nextActionDate: daysAgo(-3),
  },
  {
    id: "opp-002",
    accountId: "acc-008",
    title: "公共工事現場の混合廃棄物 一括処理契約",
    status: "OPEN",
    amount: 1200000,
    dueDate: daysAgo(-21),
    nextAction: "現場分別ルールの社内共有と単価条件提示",
    nextActionDate: daysAgo(-7),
  },
  {
    id: "opp-003",
    accountId: "acc-005",
    title: "シティタワー 年間管理契約 更新",
    status: "WON",
    amount: 3600000,
    dueDate: daysAgo(7),
    nextAction: null,
    nextActionDate: null,
  },
  {
    id: "opp-004",
    accountId: "acc-001",
    title: "新築現場の廃材月次回収（追加5現場分）",
    status: "OPEN",
    amount: 240000,
    dueDate: daysAgo(-28),
    nextAction: "見積もり提出と初回搬出スケジュール調整",
    nextActionDate: daysAgo(-5),
  },
  {
    id: "opp-005",
    accountId: "acc-009",
    title: "機密書類シュレッダー回収 + 電子マニフェスト連携",
    status: "OPEN",
    amount: 1800000,
    dueDate: daysAgo(-35),
    nextAction: "電子マニフェスト連携の運用提案資料を準備",
    nextActionDate: daysAgo(-10),
  },
  {
    id: "opp-006",
    accountId: "acc-010",
    title: "店舗リフォーム廃材 月次回収契約",
    status: "OPEN",
    amount: 850000,
    dueDate: daysAgo(-42),
    nextAction: "電子マニフェスト導入支援の試行プラン提出",
    nextActionDate: daysAgo(-12),
  },
];

// ============= Visits =============
// 過去訪問 12件 + 今日 5件 (vis-014 が IN_PROGRESS)
export const mockVisits: Visit[] = [
  {
    id: "vis-001",
    accountId: "acc-001",
    ownerId: "usr-01",
    status: "COMPLETED",
    purpose: "FOLLOW_UP",
    scheduledAt: daysAgo(20, 14, 0),
    arrivedAt: daysAgo(20, 14, 5),
    leftAt: daysAgo(20, 14, 45),
    durationMin: 40,
    arrivedLat: 33.3142, arrivedLng: 130.5122,
    routePlanId: null, opportunityId: null,
  },
  {
    id: "vis-002",
    accountId: "acc-002",
    ownerId: "usr-02",
    status: "COMPLETED",
    purpose: "NEW_PROPOSAL",
    scheduledAt: daysAgo(18, 11, 0),
    arrivedAt: daysAgo(18, 11, 2),
    leftAt: daysAgo(18, 11, 52),
    durationMin: 50,
    arrivedLat: 33.2117, arrivedLng: 130.5586,
    routePlanId: null, opportunityId: "opp-001",
  },
  {
    id: "vis-003",
    accountId: "acc-005",
    ownerId: "usr-01",
    status: "COMPLETED",
    purpose: "NEW_PROPOSAL",
    scheduledAt: daysAgo(45, 10, 0),
    arrivedAt: daysAgo(45, 10, 8),
    leftAt: daysAgo(45, 11, 8),
    durationMin: 60,
    arrivedLat: 33.3187, arrivedLng: 130.5126,
    routePlanId: null, opportunityId: null,
  },
  {
    id: "vis-004",
    accountId: "acc-004",
    ownerId: "usr-02",
    status: "COMPLETED",
    purpose: "RELATIONSHIP",
    scheduledAt: daysAgo(11, 10, 0),
    arrivedAt: daysAgo(11, 10, 8),
    leftAt: daysAgo(11, 10, 58),
    durationMin: 50,
    arrivedLat: 33.3700, arrivedLng: 130.5862,
    routePlanId: null, opportunityId: null,
  },
  {
    id: "vis-005",
    accountId: "acc-005",
    ownerId: "usr-01",
    status: "COMPLETED",
    purpose: "CONTRACT",
    scheduledAt: daysAgo(9, 13, 30),
    arrivedAt: daysAgo(9, 13, 35),
    leftAt: daysAgo(9, 14, 25),
    durationMin: 50,
    arrivedLat: 33.3187, arrivedLng: 130.5126,
    routePlanId: null, opportunityId: "opp-003",
  },
  {
    id: "vis-006",
    accountId: "acc-001",
    ownerId: "usr-01",
    status: "COMPLETED",
    purpose: "NEW_PROPOSAL",
    scheduledAt: daysAgo(7, 15, 0),
    arrivedAt: daysAgo(7, 15, 3),
    leftAt: daysAgo(7, 15, 38),
    durationMin: 35,
    arrivedLat: 33.3142, arrivedLng: 130.5122,
    routePlanId: null, opportunityId: "opp-004",
  },
  {
    id: "vis-007",
    accountId: "acc-006",
    ownerId: "usr-02",
    status: "COMPLETED",
    purpose: "RELATIONSHIP",
    scheduledAt: daysAgo(5, 14, 0),
    arrivedAt: daysAgo(5, 14, 4),
    leftAt: daysAgo(5, 14, 49),
    durationMin: 45,
    arrivedLat: 33.3768, arrivedLng: 130.6537,
    routePlanId: null, opportunityId: null,
  },
  {
    id: "vis-008",
    accountId: "acc-002",
    ownerId: "usr-02",
    status: "COMPLETED",
    purpose: "FOLLOW_UP",
    scheduledAt: daysAgo(4, 11, 30),
    arrivedAt: daysAgo(4, 11, 33),
    leftAt: daysAgo(4, 12, 13),
    durationMin: 40,
    arrivedLat: 33.2117, arrivedLng: 130.5586,
    routePlanId: null, opportunityId: "opp-001",
  },
  {
    id: "vis-009",
    accountId: "acc-003",
    ownerId: "usr-01",
    status: "COMPLETED",
    purpose: "NEW_PROPOSAL",
    scheduledAt: daysAgo(3, 14, 30),
    arrivedAt: daysAgo(3, 14, 33),
    leftAt: daysAgo(3, 15, 3),
    durationMin: 30,
    arrivedLat: 33.2988, arrivedLng: 130.5226,
    routePlanId: null, opportunityId: null,
  },
  {
    id: "vis-010",
    accountId: "acc-010",
    ownerId: "usr-01",
    status: "COMPLETED",
    purpose: "FOLLOW_UP",
    scheduledAt: daysAgo(2, 10, 0),
    arrivedAt: daysAgo(2, 10, 5),
    leftAt: daysAgo(2, 10, 45),
    durationMin: 40,
    arrivedLat: 33.3076, arrivedLng: 130.5186,
    routePlanId: null, opportunityId: "opp-006",
  },
  {
    id: "vis-011",
    accountId: "acc-009",
    ownerId: "usr-01",
    status: "COMPLETED",
    purpose: "FOLLOW_UP",
    scheduledAt: daysAgo(1, 15, 0),
    arrivedAt: daysAgo(1, 15, 2),
    leftAt: daysAgo(1, 15, 38),
    durationMin: 36,
    arrivedLat: 33.3201, arrivedLng: 130.5145,
    routePlanId: null, opportunityId: "opp-005",
  },
  {
    id: "vis-012",
    accountId: "acc-004",
    ownerId: "usr-02",
    status: "COMPLETED",
    purpose: "FOLLOW_UP",
    scheduledAt: daysAgo(1, 13, 0),
    arrivedAt: daysAgo(1, 13, 5),
    leftAt: daysAgo(1, 13, 45),
    durationMin: 40,
    arrivedLat: 33.3700, arrivedLng: 130.5862,
    routePlanId: null, opportunityId: null,
  },
  // 今日の予定
  {
    id: "vis-013",
    accountId: "acc-007",
    ownerId: "usr-02",
    status: "PLANNED",
    purpose: "RELATIONSHIP",
    scheduledAt: todayAt(9, 30),
    arrivedAt: null, leftAt: null, durationMin: null,
    arrivedLat: null, arrivedLng: null,
    routePlanId: null, opportunityId: null,
  },
  {
    id: "vis-014",
    accountId: "acc-001",
    ownerId: "usr-01",
    status: "IN_PROGRESS",
    purpose: "FOLLOW_UP",
    scheduledAt: todayAt(10, 30),
    arrivedAt: todayAt(10, 32),
    leftAt: null, durationMin: null,
    arrivedLat: 33.3142, arrivedLng: 130.5122,
    routePlanId: "rp-001", opportunityId: "opp-004",
  },
  {
    id: "vis-015",
    accountId: "acc-009",
    ownerId: "usr-01",
    status: "PLANNED",
    purpose: "NEW_PROPOSAL",
    scheduledAt: todayAt(13, 30),
    arrivedAt: null, leftAt: null, durationMin: null,
    arrivedLat: null, arrivedLng: null,
    routePlanId: "rp-001", opportunityId: "opp-005",
  },
  {
    id: "vis-016",
    accountId: "acc-002",
    ownerId: "usr-02",
    status: "PLANNED",
    purpose: "RELATIONSHIP",
    scheduledAt: todayAt(14, 0),
    arrivedAt: null, leftAt: null, durationMin: null,
    arrivedLat: null, arrivedLng: null,
    routePlanId: null, opportunityId: "opp-001",
  },
  // 田中の今日のルート: 5件構成
  {
    id: "vis-017",
    accountId: "acc-008",
    ownerId: "usr-01",
    status: "COMPLETED",
    purpose: "FOLLOW_UP",
    scheduledAt: todayAt(9, 0),
    arrivedAt: todayAt(9, 5),
    leftAt: todayAt(9, 40),
    durationMin: 35,
    arrivedLat: 33.3245, arrivedLng: 130.5275,
    routePlanId: "rp-001", opportunityId: null,
  },
  {
    id: "vis-018",
    accountId: "acc-004",
    ownerId: "usr-01",
    status: "PLANNED",
    purpose: "FOLLOW_UP",
    scheduledAt: todayAt(11, 30),
    arrivedAt: null, leftAt: null, durationMin: null,
    arrivedLat: null, arrivedLng: null,
    routePlanId: "rp-001", opportunityId: null,
  },
  {
    id: "vis-019",
    accountId: "acc-010",
    ownerId: "usr-01",
    status: "PLANNED",
    purpose: "NEW_PROPOSAL",
    scheduledAt: todayAt(15, 30),
    arrivedAt: null, leftAt: null, durationMin: null,
    arrivedLat: null, arrivedLng: null,
    routePlanId: "rp-001", opportunityId: "opp-006",
  },
];

// ============= VisitNotes =============
export const mockVisitNotes: VisitNote[] = [
  {
    id: "note-001", visitId: "vis-001", kind: "TEXT_TYPED",
    body: "大野社長と面談。月次の建築廃材回収量が増加見込み（来期 +30%）。木材分別の効率化として2tダンプの増便を提案、来週見積もり持参で再訪。",
    audioUrl: null, transcribedAt: null,
    extractedNextAction: "見積もり持参で再訪", extractedNextActionDate: daysAgo(-14),
    promotedToOpportunity: false, createdAt: daysAgo(20, 14, 42),
  },
  {
    id: "note-002", visitId: "vis-002", kind: "TEXT_TYPED",
    body: "田川工房長に解体材3区分（木材・石膏ボード・金属）の月次契約を提案。現状の混合廃棄物処理コスト比 -18% の試算で、来月から試行運用の方向で合意。",
    audioUrl: null, transcribedAt: null,
    extractedNextAction: "試行運用の単価提示", extractedNextActionDate: daysAgo(-3),
    promotedToOpportunity: true, createdAt: daysAgo(18, 11, 53),
  },
  {
    id: "note-003", visitId: "vis-003", kind: "TEXT_TYPED",
    body: "シティタワー 高橋管理責任者に年間管理契約の更新を提案。テナント入居率 92% で書類量が増加、シュレッダー回収を週1→週2に増便、契約金額は据置で合意の方向。",
    audioUrl: null, transcribedAt: null,
    extractedNextAction: "週2回シュレッダーの試行スケジュール提示", extractedNextActionDate: daysAgo(-10),
    promotedToOpportunity: true, createdAt: daysAgo(45, 11, 8),
  },
  {
    id: "note-004", visitId: "vis-004", kind: "TEXT_TYPED",
    body: "古賀代表と月次定例。RC解体現場でのコンクリート分別精度を上げる方針。混合廃棄物率を 25% → 15% 目標、現場常駐の段取りを来週決定。",
    audioUrl: null, transcribedAt: null,
    extractedNextAction: "現場常駐スタッフのアサイン", extractedNextActionDate: daysAgo(-7),
    promotedToOpportunity: false, createdAt: daysAgo(11, 10, 55),
  },
  {
    id: "note-005", visitId: "vis-005", kind: "TEXT_TYPED",
    body: "高橋管理責任者と契約更新の最終調整。年間契約金額 360万円で合意、書面は本社経由で来週送付。テナント追加入居時の単価条件も盛り込み。",
    audioUrl: null, transcribedAt: null,
    extractedNextAction: "契約書送付", extractedNextActionDate: daysAgo(-1),
    promotedToOpportunity: true, createdAt: daysAgo(9, 14, 22),
  },
  {
    id: "note-006", visitId: "vis-006", kind: "TEXT_TYPED",
    body: "大野建築フォロー。前回提案した2tダンプ増便案、現場5箇所での試行に好印象。中村現場監督も同席で前向き。来月から月次回収契約に切替予定で、見積もり書面と試行スケジュールを進める。",
    audioUrl: null, transcribedAt: null,
    extractedNextAction: "見積もり書面と試行スケジュール提出", extractedNextActionDate: daysAgo(-5),
    promotedToOpportunity: true, createdAt: daysAgo(7, 15, 38),
  },
  {
    id: "note-007", visitId: "vis-007", kind: "TEXT_TYPED",
    body: "太田工場長と切粉・スクラップの引取単価交渉。鉄相場上昇で単価見直し、月次70万円規模の取引で +5% の改定で合意。昇降機更新で来月以降の発生量増加見込み。",
    audioUrl: null, transcribedAt: null,
    extractedNextAction: "単価改定の正式書面", extractedNextActionDate: daysAgo(-12),
    promotedToOpportunity: false, createdAt: daysAgo(5, 14, 50),
  },
  {
    id: "note-008", visitId: "vis-008", kind: "TEXT_TYPED",
    body: "田川工房長フォロー。先週の3区分試行は順調、混合率が平均 8% まで下がった。来月から本契約に移行で確定、初回搬出は月初2日。",
    audioUrl: null, transcribedAt: null,
    extractedNextAction: "本契約書面と初回搬出日確定", extractedNextActionDate: daysAgo(-3),
    promotedToOpportunity: false, createdAt: daysAgo(4, 12, 13),
  },
  {
    id: "note-009", visitId: "vis-009", kind: "TEXT_TYPED",
    body: "山内工場長へ初回提案訪問。金属屑（鉄・アルミ・銅）の買取単価表を提示、競合比較でアルミ単価が +8% 有利と説明。次回は計量データを持参して再相談したいとのこと。",
    audioUrl: null, transcribedAt: null,
    extractedNextAction: "計量データ持参で再訪", extractedNextActionDate: daysAgo(-7),
    promotedToOpportunity: false, createdAt: daysAgo(3, 15, 5),
  },
  {
    id: "note-010", visitId: "vis-010", kind: "TEXT_TYPED",
    body: "西鉄リフォーム 永野店長と電子マニフェスト導入の試行プランを共有。月10〜15現場で運用、紙マニフェスト併用期間は1ヶ月。来月のリフォーム工事から段階導入を検討中。",
    audioUrl: null, transcribedAt: null,
    extractedNextAction: "試行プラン正式書面と導入スケジュール", extractedNextActionDate: daysAgo(-15),
    promotedToOpportunity: false, createdAt: daysAgo(2, 10, 45),
  },
  {
    id: "note-011", visitId: "vis-011", kind: "TEXT_TYPED",
    body: "永田ビル管理長から機密書類シュレッダー回収の頻度見直し相談。現在月1→月2 への変更案。電子マニフェストとの連携で運用負荷を軽減できる旨を提案、次回提案資料持参。",
    audioUrl: null, transcribedAt: null,
    extractedNextAction: "電子マニフェスト連携 提案資料持参", extractedNextActionDate: daysAgo(-9),
    promotedToOpportunity: false, createdAt: daysAgo(1, 15, 35),
  },
  {
    id: "note-012", visitId: "vis-012", kind: "TEXT_TYPED",
    body: "古賀代表と前回の続き。現場常駐スタッフは2現場ローテーションで開始。マニフェスト電子化の話も持ち上がり、別途打合せセット予定。",
    audioUrl: null, transcribedAt: null,
    extractedNextAction: "電子マニフェスト導入の打合せ日程", extractedNextActionDate: daysAgo(-7),
    promotedToOpportunity: false, createdAt: daysAgo(1, 13, 45),
  },
  {
    id: "note-013", visitId: "vis-017", kind: "TEXT_TYPED",
    body: "新井工事部長と公共工事現場の混合廃棄物処理を協議。来週からの新現場で試行運用、現場分別ルールを共有。電子マニフェスト併用で報告書類の自動化も提案。",
    audioUrl: null, transcribedAt: null,
    extractedNextAction: "試行運用の単価条件と現場ルール書面", extractedNextActionDate: todayAt(0, 0),
    promotedToOpportunity: false, createdAt: todayAt(9, 38),
  },
];

// ============= RoutePlans =============
export const mockRoutePlans: RoutePlan[] = [
  {
    id: "rp-001",
    ownerId: "usr-01",
    planDate: todayAt(0, 0),
    status: "DRAFT",
    startLat: 33.3194, startLng: 130.5092, startLabel: "久留米本社（JR久留米駅前）",
    endLat: 33.3194, endLng: 130.5092, endLabel: "久留米本社（JR久留米駅前）",
    orderedVisitIds: "vis-017,vis-014,vis-018,vis-015,vis-019",
    totalDistanceM: 32000,
    totalDurationS: 4500,
  },
];
